---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: latest

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
      box_url: https://vagrantcloud.com/bento/ubuntu-16.04
      box_check_update: true

suites:
  - name: default
    run_list:
    - recipe[qmk::default]
    verifier:
      controls:
      - packages
