---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_version: latest
  client_rb:
    chef_license: accept


verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
      box_url: https://vagrantcloud.com/bento/ubuntu-16.04
      box_check_update: true

suites:
  - name: default
    run_list:
    - recipe[qmk::default]
    verifier:
      controls:
      - packages
