---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: latest

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[qmk::default]
    verifier:
      controls:
      - packages
